# Generated by Django 3.2.16 on 2022-12-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopCrud', '0003_auto_20221216_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
    ]
